language: node_js
node_js:
  - "12"
# branches:
#   only:
#     - master
# cache:
#   directories:
#     - node_modules
# before_install:
#   - mysql -e 'CREATE DATABASE IF NOT EXISTS bigwalletdb;'
  
# script:
  # - npm run lint
  # - npm run build
  # - npm test